#!/usr/local/bin/perl
 
$a = 10;
@b = (25, 45, 47);
$c = "abcd";
$d = "abcde";
$e = \@b;
$f = \@$e;
@g = @$e;
printf "\$e: $e, \$f: $f\n";

# while loop execution
while( $a < 20 ){
   printf "Value of a: $a\n";
   $a = $a + 1;
   if ($c gt $d) {
      print $c;
  } 
}
