#!/usr/bin/env python

import sys
from src import *

if __name__ == "__main__":

    argLen = len(sys.argv)
    if argLen < 2:
	print "Please provide IR file for code generation"

    else:
	filePtr = open(str(sys.argv[1]), 'r')
        codeGen = CodeGenerator(filePtr.read(), str(sys.argv[1]))
        codeGen.GenBasicBlocks()
        #codeGen.PrintBasicBlocks()
        codeGen.BuildCode()


