#!/usr/bin/env python
import sys

# Import lexer and parser libraries
from src import *

if __name__ == "__main__":

    myLexer = LEXER.Lexer()
    myLexer.build()

    myParser = PARSER.Parser()
    myParser.set_tokens(myLexer.tokens)
    myParser.build()

    argLen = len(sys.argv)
    if argLen < 2:
        print "Please provide file for parsing"
    else:
        filePtr = open(str(sys.argv[1]), 'r')
        myParser.parse(filePtr.read())
